defaults:
  executable: ais_bench
  request_rate: 0
  retries: 3
  max_output_tokens: 32768
  concurrency: 128
  num_warmups: 0
  dump_details: true
  generation_kwargs:
    temperature: 1
    top_p: 0.95
    repetition_penalty: 1
    ignore_eos: false

profiles:
  gsm8k_dsv4_flash_32k:
    description: 使用 DeepSeek V4 Flash 运行最大输出 32K 的 GSM8K 0-shot CoT 精度测试
    dataset: gsm8k
    path: aisbench_workspace/datasets/gsm8k/test.jsonl
    generation_kwargs:
      chat_template_kwargs:
        enable_thinking: true
  gpqa_dsv4_flash_32k:
    description: 使用 DeepSeek V4 Flash 运行最大输出 32K 的 GPQA Diamond 0-shot CoT 精度测试
    dataset: gpqa
    path: aisbench_workspace/datasets/gpqa/gpqa_diamond.csv
    generation_kwargs:
      chat_template_kwargs:
        enable_thinking: true
