defaults:
  executable: ais_bench
  request_rate: 0
  temperature: 0
  repetition_penalty: 1
  ignore_eos: true
  retries: 3
  repeats: 1
  concurrency: 4
  stats: [Average, Min, Max, Median, P90, P95, P99]

profiles:
  concurrency_4:
    description: 4 并发请求参数
    concurrency: 4
  concurrency_8:
    description: 8 并发请求参数
    concurrency: 8
  concurrency_128:
    description: 128 用于精度测试
    concurrency: 128
  warmup:
    description: 手动预热请求参数，结果不纳入性能统计
    concurrency: 1
