models:
  qwen3_30b_a3b_w8a8:
    description: 用于最基本功能冒烟测试的 Qwen 模型
    model_tag: /home/weight/Qwen3-30B-A3B-W8A8
    arguments:
      --served-model-name: qwen3-30b-a3b-w8a8
      --quantization: ascend

  deepseek_v4_flash:
    description: 用于长序列、CPP、SRF 和精度测试的 DeepSeek 模型
    model_tag: /home/weight/DeepSeek-V4-Flash-w8a8-mtp
    arguments:
      --served-model-name: deepseek-v4-flash
      --quantization: ascend
      --max-model-len: 66560
      --tokenizer-mode: deepseek_v4
      --tool-call-parser: deepseek_v4
      --reasoning-parser: deepseek_v4
      --enable-auto-tool-choice: true
      --enable-expert-parallel: true

  deepseek_v4_flash_server14_16cards:
    description: server-14-16cards 专用 DeepSeek V4 Flash W8A8 MTP 模型
    model_tag: /home/DeepSeek-V4-Flash-w8a8-mtp
    arguments:
      --served-model-name: deepseek-v4-flash
      --quantization: ascend
      --tokenizer-mode: deepseek_v4
      --tool-call-parser: deepseek_v4
      --reasoning-parser: deepseek_v4
      --enable-auto-tool-choice: true
      --enable-expert-parallel: true

  deepseek_v4_flash_server27_8cards:
    description: server-27-8cards 专用 DeepSeek V4 Flash W8A8 MTP 模型
    model_tag: /home/weight/DeepSeek-V4-Flash-w8a8-mtp
    arguments:
      --served-model-name: deepseek-v4-flash
      --quantization: ascend
      --max-model-len: 66560
      --tokenizer-mode: deepseek_v4
      --tool-call-parser: deepseek_v4
      --reasoning-parser: deepseek_v4
      --enable-auto-tool-choice: true
      --enable-expert-parallel: true

  deepseek_v4_pro_w4a8_0813:
    description: 双机 PD 性能测试使用的 DeepSeek V4 Pro W4A8 0813 模型
    model_tag: /mnt/share/DeepSeekV4-pro-0813-w4a8
    arguments:
      --served-model-name: deepseek-v4-pro
      --quantization: ascend
      --max-model-len: 1048576
      --tokenizer-mode: deepseek_v4
      --tool-call-parser: deepseek_v4
      --reasoning-parser: deepseek_v4
      --enable-auto-tool-choice: true
      --enable-expert-parallel: true
      --no-disable-hybrid-kv-cache-manager: true
      --model-loader-extra-config:
        enable_multithread_load: true
        num_threads: 128
      --speculative-config:
        num_speculative_tokens: 1
        method: mtp
        enforce_eager: true

  deepseek_v4_flash_w8a8_mtp_pd:
    description: 单机 A3 PD 性能测试使用的 DeepSeek V4 Flash W8A8 模型
    model_tag: /home/weight/DeepSeek-V4-Flash-w8a8-mtp
    arguments:
      --served-model-name: deepseek-v4-flash
      --quantization: ascend
      --max-model-len: 1048576
      --tokenizer-mode: deepseek_v4
      --tool-call-parser: deepseek_v4
      --reasoning-parser: deepseek_v4
      --enable-auto-tool-choice: true
      --enable-expert-parallel: true
      --no-disable-hybrid-kv-cache-manager: true
      --model-loader-extra-config:
        enable_multithread_load: true
        num_threads: 128
